school/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', function () {
    return view('welcome');
});

Route::auth();
Route::resource("classrooms","ClassroomController");
Route::resource("classrooms.blogs","BlogController");
Route::resource("comments","CommentController");
Route::resource("classrooms.assignments","AssignmentController");
Route::resource("classrooms.messages","MessageController");
Route::resource("classrooms.videos","VideoController");

school/app/Assignment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Assignment extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $fillable = ['title','content','status','startdate','enddate','priority'];
    public function classroom()
    {
        return $this->belongsTo('App\Classroom');
    }
}

school/app/Http/Controllers/AssignmentController.php
<?php namespace App\Http\Controllers;
use App\Classroom;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Assignment;
use Illuminate\Http\Request;
use App\Policies\AssignmentPolicy;

class AssignmentController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function __construct()
	{
		$this->middleware('auth');
		$this->middleware('throttle:30,1');
	}
	public function index($classroomid)
	{
		$assignments = Assignment::orderBy('id', 'desc')->paginate(10);

		return view('assignments.index', compact('assignments','classroomid'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create($classroomid)
	{
		return view('assignments.create',compact('classroomid'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store($classroomid,Request $request)
	{

		$this->validate($request, [
				'title' => 'required|max:255',
				'content' => 'required|max:65000',
				'status' => 'required|between:0,1',
				'startdate' => 'date|after:enddate',
				'enddate' => 'date|after:startdate',
				'priority' => 'required|between:0,2',
		]);
		$assignment = new Assignment();

		$assignment->title = $request->input("title");
        $assignment->content = $request->input("content");
        $assignment->status = $request->input("status");
        $assignment->startdate = $request->input("startdate");
        $assignment->enddate = $request->input("enddate");
        $assignment->priority = $request->input("priority");
		$assignment->classroom_id=$classroomid;
		$assignment->user_id=Auth::user()->id;
		$this->authorize('create',$assignment);
		$assignment->save();

		return redirect()->route('classrooms.assignments.index',compact('classroomid'))->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($classroomid,$id)
	{
		$assignment = Assignment::findOrFail($id);

		return view('assignments.show', compact('assignment','classroomid'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($classroomid,$id)
	{
		$assignment = Assignment::findOrFail($id);
		$this->authorize('update', $assignment);
		return view('assignments.edit', compact('assignment','classroomid'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update($classroomid,Request $request, $id)
	{
		$this->validate($request, [
				'title' => 'required|max:255',
				'content' => 'required|max:65000',
				'status' => 'required|between:0,1',
				'startdate' => 'date|after:enddate',
				'enddate' => 'date|after:startdate',
				'priority' => 'required|between:0,2',
		]);
		$assignment = Assignment::findOrFail($id);
		$this->authorize('update', $assignment);
		$assignment->title = $request->input("title");
        $assignment->content = $request->input("content");
        $assignment->status = $request->input("status");
        $assignment->startdate = $request->input("startdate");
        $assignment->enddate = $request->input("enddate");
        $assignment->priority = $request->input("priority");

		$assignment->save();

		return redirect()->route('classrooms.assignments.index',compact('classroomid'))->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($classroomid,$id)
	{
		$assignment = Assignment::findOrFail($id);
		$this->authorize('delete', $assignment);
		$assignment->delete();

		return redirect()->route('classrooms.assignments.index',compact('classroomid'))->with('message', 'Item deleted successfully.');
	}

}

school/resources/views/assignments/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Assignments / Create </h1>
    </div>
@endsection

@section('content')
    @include('common.errors')
    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('classrooms.assignments.store',$classroomid) }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('title')) has-error @endif">
                       <label for="title-field">Title</label>
                    <input type="text" id="title-field" name="title" class="form-control" value="{{ old("title") }}"/>
                       @if($errors->has("title"))
                        <span class="help-block">{{ $errors->first("title") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('content')) has-error @endif">
                       <label for="content-field">Content</label>
                    <input type="text" id="content-field" name="content" class="form-control editor" value="{{ old("content") }}"/>
                       @if($errors->has("content"))
                        <span class="help-block">{{ $errors->first("content") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('status')) has-error @endif">
                       <label for="status-field">Status</label>
                    <input type="text" id="status-field" name="status" class="form-control" value="{{ old("status") }}"/>
                       @if($errors->has("status"))
                        <span class="help-block">{{ $errors->first("status") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('startdate')) has-error @endif">
                       <label for="startdate-field">Startdate</label>
                    <input type="text" id="startdate-field" name="startdate" class="form-control" value="{{ old("startdate") }}"/>
                       @if($errors->has("startdate"))
                        <span class="help-block">{{ $errors->first("startdate") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('enddate')) has-error @endif">
                       <label for="enddate-field">Enddate</label>
                    <input type="text" id="enddate-field" name="enddate" class="form-control" value="{{ old("enddate") }}"/>
                       @if($errors->has("enddate"))
                        <span class="help-block">{{ $errors->first("enddate") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('priority')) has-error @endif">
                       <label for="priority-field">Priority</label>
                    <input type="text" id="priority-field" name="priority" class="form-control" value="{{ old("priority") }}"/>
                       @if($errors->has("priority"))
                        <span class="help-block">{{ $errors->first("priority") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('classrooms.assignments.index',$classroomid) }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

school/resources/views/assignments/edit.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Assignments / Edit #{{$assignment->id}}</h1>
    </div>
@endsection

@section('content')
    @include('common.errors')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('classrooms.assignments.update',[$classroomid, $assignment->id]) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('title')) has-error @endif">
                       <label for="title-field">Title</label>
                    <input type="text" id="title-field" name="title" class="form-control" value="{{ $assignment->title }}"/>
                       @if($errors->has("title"))
                        <span class="help-block">{{ $errors->first("title") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('content')) has-error @endif">
                       <label for="content-field">Content</label>
                    <input type="text" id="content-field" name="content" class="form-control" value="{{ $assignment->content }}"/>
                       @if($errors->has("content"))
                        <span class="help-block">{{ $errors->first("content") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('status')) has-error @endif">
                       <label for="status-field">Status</label>
                    <input type="text" id="status-field" name="status" class="form-control" value="{{ $assignment->status }}"/>
                       @if($errors->has("status"))
                        <span class="help-block">{{ $errors->first("status") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('startdate')) has-error @endif">
                       <label for="startdate-field">Startdate</label>
                    <input type="text" id="startdate-field" name="startdate" class="form-control" value="{{ $assignment->startdate }}"/>
                       @if($errors->has("startdate"))
                        <span class="help-block">{{ $errors->first("startdate") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('enddate')) has-error @endif">
                       <label for="enddate-field">Enddate</label>
                    <input type="text" id="enddate-field" name="enddate" class="form-control" value="{{ $assignment->enddate }}"/>
                       @if($errors->has("enddate"))
                        <span class="help-block">{{ $errors->first("enddate") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('priority')) has-error @endif">
                       <label for="priority-field">Priority</label>
                    <input type="text" id="priority-field" name="priority" class="form-control" value="{{ $assignment->priority }}"/>
                       @if($errors->has("priority"))
                        <span class="help-block">{{ $errors->first("priority") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('classrooms.assignments.index',$classroomid) }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

school/resources/views/assignments/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Assignments
            <a class="btn btn-success pull-right" href="{{ route('classrooms.assignments.create',$classroomid) }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($assignments->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>TITLE</th>
                        <th>CONTENT</th>
                        <th>STATUS</th>
                        <th>STARTDATE</th>
                        <th>ENDDATE</th>
                        <th>PRIORITY</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($assignments as $assignment)
                            <tr>
                                <td>{{$assignment->id}}</td>
                                <td>{{$assignment->title}}</td>
                    <td>{{$assignment->content}}</td>
                    <td>{{$assignment->status}}</td>
                    <td>{{$assignment->startdate}}</td>
                    <td>{{$assignment->enddate}}</td>
                    <td>{{$assignment->priority}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('classrooms.assignments.show',[$classroomid, $assignment->id]) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    @can('update', $assignment)
                                        <a class="btn btn-xs btn-warning" href="{{ route('classrooms.assignments.edit',[$classroomid, $assignment->id]) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    @endcan
                                    @can('delete',$assignment)
                                    <form action="{{ route('classrooms.assignments.destroy', [$classroomid,$assignment->id]) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                    @endcan
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $assignments->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

school/resources/views/assignments/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Assignments / Show #{{$assignment->id}}</h1>
        <form action="{{ route('classrooms.assignments.destroy',[$classroomid, $assignment->id]) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('classrooms.assignments.edit', [$classroomid,$assignment->id]) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="title">TITLE</label>
                     <p class="form-control-static">{{$assignment->title}}</p>
                </div>
                    <div class="form-group">
                     <label for="content">CONTENT</label>
                     <p class="form-control-static">{{$assignment->content}}</p>
                </div>
                    <div class="form-group">
                     <label for="status">STATUS</label>
                     <p class="form-control-static">{{$assignment->status}}</p>
                </div>
                    <div class="form-group">
                     <label for="startdate">STARTDATE</label>
                     <p class="form-control-static">{{$assignment->startdate}}</p>
                </div>
                    <div class="form-group">
                     <label for="enddate">ENDDATE</label>
                     <p class="form-control-static">{{$assignment->enddate}}</p>
                </div>
                    <div class="form-group">
                     <label for="priority">PRIORITY</label>
                     <p class="form-control-static">{{$assignment->priority}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('classrooms.assignments.index',$classroomid) }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection