school/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', function () {
    return view('welcome');
});

Route::auth();
Route::resource("classrooms","ClassroomController");
Route::resource("classrooms.blogs","BlogController");
Route::resource("comments","CommentController");
Route::resource("classrooms.assignments","AssignmentController");
Route::resource("classrooms.messages","MessageController");
Route::resource("classrooms.videos","VideoController");

school/app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Message extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $fillable = ['title','content','status','to'];
}

school/app/Http/Controllers/MessageController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Auth;
use App\Policies\MessagePolicy;
use App\Message;
use Illuminate\Http\Request;

class MessageController extends Controller {

	public function __construct()
	{
		$this->middleware('auth');
		$this->middleware('throttle:30,1');
	}
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */

	public function index($classroomid)
	{
		$messages = Message::orderBy('id', 'desc')->paginate(10);

		return view('messages.index', compact('messages','classroomid'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create($classroomid)
	{
		return view('messages.create',compact('classroomid'));
	}

	/**
	 * Store a newly created resource in storage.
	 *s
	 * @param Request $request
	 * @return Response
	 */
	public function store($classroomid,Request $request)
	{
		$this->validate($request, [
				'title' => 'required|max:255',
				'content' => 'required|max:2000',
				'status' => 'required|between:0,1',
				'to' => 'exists:users,id',
		]);
		$message = new Message();

		$message->title = $request->input("title");
        $message->content = $request->input("content");
        $message->status = $request->input("status");
        $message->to = $request->input("to");
		$message->classroom_id=$classroomid;
		$message->user_id=Auth::user()->id;
		$this->authorize('create',$message);
		$message->save();

		return redirect()->route('classrooms.messages.index',compact('classroomid'))->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($classroomid,$id)
	{
		$message = Message::findOrFail($id);

		return view('messages.show', compact('message','classroomid'));
	}
	public function destroy($classroomid,$id)
	{
		$message = Message::findOrFail($id);
		$this->authorize('delete', $message);
		$message->delete();

		return redirect()->route('classrooms.messages.index','classroomid')->with('message', 'Item deleted successfully.');
	}

}

school/resources/views/messages/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Messages / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('classrooms.messages.store',$classroomid) }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('title')) has-error @endif">
                       <label for="title-field">Title</label>
                    <input type="text" id="title-field" name="title" class="form-control" value="{{ old("title") }}"/>
                       @if($errors->has("title"))
                        <span class="help-block">{{ $errors->first("title") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('content')) has-error @endif">
                       <label for="content-field">Content</label>
                    <input type="text" id="content-field" name="content" class="form-control" value="{{ old("content") }}"/>
                       @if($errors->has("content"))
                        <span class="help-block">{{ $errors->first("content") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('status')) has-error @endif">
                       <label for="status-field">Status</label>
                    <input type="text" id="status-field" name="status" class="form-control" value="{{ old("status") }}"/>
                       @if($errors->has("status"))
                        <span class="help-block">{{ $errors->first("status") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('to')) has-error @endif">
                       <label for="to-field">To</label>
                    <input type="text" id="to-field" name="to" class="form-control" value="{{ old("to") }}"/>
                       @if($errors->has("to"))
                        <span class="help-block">{{ $errors->first("to") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('classrooms.messages.index',$classroomid) }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

school/resources/views/messages/edit.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Messages / Edit #{{$message->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('classrooms.messages.update', [$classroomid,$message->id]) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('title')) has-error @endif">
                       <label for="title-field">Title</label>
                    <input type="text" id="title-field" name="title" class="form-control" value="{{ $message->title }}"/>
                       @if($errors->has("title"))
                        <span class="help-block">{{ $errors->first("title") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('content')) has-error @endif">
                       <label for="content-field">Content</label>
                    <input type="text" id="content-field" name="content" class="form-control" value="{{ $message->content }}"/>
                       @if($errors->has("content"))
                        <span class="help-block">{{ $errors->first("content") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('status')) has-error @endif">
                       <label for="status-field">Status</label>
                    <input type="text" id="status-field" name="status" class="form-control" value="{{ $message->status }}"/>
                       @if($errors->has("status"))
                        <span class="help-block">{{ $errors->first("status") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('to')) has-error @endif">
                       <label for="to-field">To</label>
                    <input type="text" id="to-field" name="to" class="form-control" value="{{ $message->to }}"/>
                       @if($errors->has("to"))
                        <span class="help-block">{{ $errors->first("to") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('classrooms.messages.index',$classroomid) }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

school/resources/views/messages/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Messages
            <a class="btn btn-success pull-right" href="{{ route('classrooms.messages.create',$classroomid) }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($messages->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>TITLE</th>
                        <th>CONTENT</th>
                        <th>STATUS</th>
                        <th>TO</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($messages as $message)
                            <tr>
                                <td>{{$message->id}}</td>
                                <td>{{$message->title}}</td>
                    <td>{{$message->content}}</td>
                    <td>{{$message->status}}</td>
                    <td>{{$message->to}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('classrooms.messages.show',[$classroomid, $message->id]) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    @can('update', $message)
                                    <a class="btn btn-xs btn-warning" href="{{ route('classrooms.messages.edit', [$classroomid,$message->id]) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                   @endcan
                                    @can('delete', $message)
                                    <form action="{{ route('classrooms.messages.destroy',[$classroomid ,$message->id]) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                    @endcan
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $messages->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

school/resources/views/messages/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Messages / Show #{{$message->id}}</h1>
        <form action="{{ route('messages.destroy', $message->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('messages.edit', $message->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="title">TITLE</label>
                     <p class="form-control-static">{{$message->title}}</p>
                </div>
                    <div class="form-group">
                     <label for="content">CONTENT</label>
                     <p class="form-control-static">{{$message->content}}</p>
                </div>
                    <div class="form-group">
                     <label for="status">STATUS</label>
                     <p class="form-control-static">{{$message->status}}</p>
                </div>
                    <div class="form-group">
                     <label for="to">TO</label>
                     <p class="form-control-static">{{$message->to}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('messages.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection