school/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', function () {
    return view('welcome');
});

Route::auth();
Route::resource("classrooms","ClassroomController");
Route::resource("classrooms.blogs","BlogController");
Route::resource("comments","CommentController");
Route::resource("classrooms.assignments","AssignmentController");
Route::resource("classrooms.messages","MessageController");
Route::resource("classrooms.videos","VideoController");

school/app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Blog extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $fillable = ['title','content','status'];

    public function classroom()
    {
        return $this->belongsTo('App\Classroom');
    }
}

school/app/Http/Controllers/BlogController.php
<?php namespace App\Http\Controllers;

use App\Classroom;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Mail;
use App\Blog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Policies\BlogPolicy;

class BlogController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function __construct()
	{
		$this->middleware('auth');
		$this->middleware('throttle:30,1');
	}
	public function index($classroomid)
	{
		$blogs = Blog::orderBy('id', 'desc')->paginate(10);
		return view('blogs.index', compact('blogs','classroomid'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create($classroomid)
	{

		return view('blogs.create',compact('classroomid'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store($classroomid,Request $request)
	{

		$this->validate($request, [
				'title' => 'required|max:255',
				'content' => 'required|max:65000',
				'status' => 'required|between:0,1',
		]);
		$blog = new Blog();

		$blog->title = $request->input("title");
        $blog->content = $request->input("content");
        $blog->status = $request->input("status");
		$blog->classroom_id=$classroomid;
		$blog->user_id=Auth::user()->id;
		$this->authorize('create',$blog);
		$blog->save();
		Mail::queue('emails.welcome', compact($blog), function ($message) {
			$message->from('vaidhyanathan93@hotmail.com', 'openclassrooms');
			$message->to('vaidhyanathan93@gmail.com');
		});
		return redirect()->route('classrooms.blogs.index',compact('classroomid'))->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($classroomid,$id)
	{
		$blog = Blog::findOrFail($id);

		return view('blogs.show', compact('blog','classroomid'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($classroomid,$id)
	{
		$blog = Blog::findOrFail($id);
		$this->authorize('update', $blog);
		return view('blogs.edit', compact('blog','classroomid'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update($classroomid,Request $request, $id)
	{
		$this->validate($request, [
				'title' => 'required|max:255',
				'content' => 'required|max:65000',
				'status' => 'required|between:0,1',
		]);
		$blog = Blog::findOrFail($id);
		$this->authorize('update', $blog);
		$blog->title = $request->input("title");
        $blog->content = $request->input("content");
        $blog->status = $request->input("status");

		$blog->save();

		return redirect()->route('classrooms.blogs.index',compact('classroomid'))->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($classroomid,$id)
	{
		$blog = Blog::findOrFail($id);
		$this->authorize('delete', $blog);
		$blog->delete();

		return redirect()->route('classrooms.blogs.index',compact('classroomid'))->with('message', 'Item deleted successfully.');
	}

}

school/resources/views/blogs/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Create blog </h1>
    </div>
@endsection

@section('content')
    @include('common.errors')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('classrooms.blogs.store',$classroomid) }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('title')) has-error @endif">
                       <label for="title-field">Title</label>
                    <input type="text" id="title-field" name="title" class="form-control" value="{{ old("title") }}"/>
                       @if($errors->has("title"))
                        <span class="help-block">{{ $errors->first("title") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('content')) has-error @endif">
                       <label for="content-field">Content</label>
                    <input type="text" id="content-field" name="content" class="form-control" value="{{ old("content") }}"/>
                       @if($errors->has("content"))
                        <span class="help-block">{{ $errors->first("content") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('status')) has-error @endif">
                       <label for="status-field">Status</label>
                    <input type="text" id="status-field" name="status" class="form-control" value="{{ old("status") }}"/>
                       @if($errors->has("status"))
                        <span class="help-block">{{ $errors->first("status") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('classrooms.blogs.index',$classroomid) }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

school/resources/views/blogs/edit.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Blogs / Edit #{{$blog->id}}</h1>
    </div>
@endsection

@section('content')
    @include('common.errors')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('classrooms.blogs.update', [$classroomid,$blog->id]) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('title')) has-error @endif">
                       <label for="title-field">Title</label>
                    <input type="text" id="title-field" name="title" class="form-control" value="{{ $blog->title }}"/>
                       @if($errors->has("title"))
                        <span class="help-block">{{ $errors->first("title") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('content')) has-error @endif">
                       <label for="content-field">Content</label>
                    <input type="text" id="content-field" name="content" class="form-control" value="{{ $blog->content }}"/>
                       @if($errors->has("content"))
                        <span class="help-block">{{ $errors->first("content") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('status')) has-error @endif">
                       <label for="status-field">Status</label>
                    <input type="text" id="status-field" name="status" class="form-control" value="{{ $blog->status }}"/>
                       @if($errors->has("status"))
                        <span class="help-block">{{ $errors->first("status") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('classrooms.blogs.index',$classroomid) }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

school/resources/views/blogs/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Blogs
            <a class="btn btn-success pull-right" href="{{ route('classrooms.blogs.create',$classroomid) }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($blogs->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>TITLE</th>
                        <th>CONTENT</th>
                        <th>STATUS</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($blogs as $blog)
                            <tr>
                                <td>{{$blog->id}}</td>
                                <td>{{$blog->title}}</td>
                    <td>{{$blog->content}}</td>
                    <td>{{$blog->status}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('classrooms.blogs.show',[ $classroomid,$blog->id]) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    @can('update', $blog)
                                    <a class="btn btn-xs btn-warning" href="{{ route('classrooms.blogs.edit',[$classroomid, $blog->id]) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    @endcan
                                    @can('delete', $blog)
                                    <form action="{{ route('classrooms.blogs.destroy',[$classroomid, $blog->id]) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                    @endcan
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $blogs->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

school/resources/views/blogs/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Blogs / Show #{{$blog->id}}</h1>
    @can('delete', $blog)
        <form action="{{ route('classrooms.blogs.destroy', [$classroomid,$blog->id]) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">

                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    @endcan
    @can('update', $blog)
    <a class="btn btn-warning btn-group" role="group" href="{{ route('classrooms.blogs.edit',[$classroomid, $blog->id]) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
    @endcan
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="title">TITLE</label>
                     <p class="form-control-static">{{$blog->title}}</p>
                </div>
                    <div class="form-group">
                     <label for="content">CONTENT</label>
                     <p class="form-control-static">{{$blog->content}}</p>
                </div>
                    <div class="form-group">
                     <label for="status">STATUS</label>
                     <p class="form-control-static">{{$blog->status}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('classrooms.blogs.index',$classroomid) }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection